#!/bin/bash
cd /tmp/rec
rm -rf .repo
cd /tmp/rec
cd device/oppo/CPH1861
patchelf --set-interpreter /system/bin/linker64 recovery/root/system/bin/*
cd /tmp/rec
source build/envsetup.sh
lunch omni_CPH1861-eng
export SKIP_API_CHECKS=true
export SKIP_ABI_CHECKS=true
export ALLOW_MISSING_DEPENDENCIES=true
cd /tmp/rec
export CCACHE_DIR=/tmp/ccache  ##use additional flags if you need(optional)
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1

ccache -M 30G
ccache -o compression=true
ccache -z
ccache -c

make_rec(){
	mka recoveryimage
	curl -sL https://git.io/file-transfer | sh
	./transfer wet out/target/product/CPH1861/*.img
    ./transfer wet out/target/product/CPH1861.zip
    ./transfer wet out/target/product/CPH1861/*Official*.zip
	./transfer wet out/target/product/CPH1861/*OFFICIAL*.zip
    ./transfer wet out/target/product/CPH1861/*Add*.zip
}

make_rec
